### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by lockie**
Hello!
This PR fixes the Windows build as per [official Travis documentation](https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2).

### CODE REVIEW

**Comment by snmsts** [comment]
currently I failed to run travis for this account. I'm appreciate if you can make windows build for github actions.

**Comment by lockie** [comment]
Oh, I had a suspicion that you don't use Travis anymore. All right, I'll have a look at those github actions later (haven't had any experience with them yet).

**Comment by snmsts** [comment]
thank you. I don't use travis because they don't reply for my email asking how to have quota for OSS for this repo... I already exceed the allowance by daily build. and not maintain this project for half years? I didn't notice it became like this. my bad and shame. sorry for inconvenience.

**Comment by lockie** [comment]
No problem. I'll see what I can help with.

**Pull request closed without merging**
